### ISSUE TITLE
console.sst.dev does not load at all on mac M1

### ISSUE THREAD

**Issue by Harrison97** [sst/guide#682]
I am using a Mac M1 so I assume this may be an issue here, maybe not.

However I am simply trying to do the QuickStart app and everything deploys fine and I can call my APIs etc, but I cannot actually use the web console for debugging. I have the debug stack deployed and I have it running locally. Still no luck and the screen is just stuck on this:
![Screen Shot 2022-07-12 at 20 16 11](https://user-images.githubusercontent.com/16231162/178627580-bb6b3868-eb9d-460d-a88f-be5d71b83f78.png)

With these Errors:
![Screen Shot 2022-07-12 at 20 16 48](https://user-images.githubusercontent.com/16231162/178627646-9591c2d4-040f-4d13-abaa-97fa8c78d456.png)

Has anyone run into a similar issue on M1 or otherwise? Any help would be great. I could be possibly missing something very basic but any help would be great.

Thanks.

**Comment by jayair** [comment]
Which browser are you using? Btw, the Discord is the best place for this: https://discord.gg/sst

**Comment by flea89** [comment]
Hello, I'm experiencing the same problem on Chrome (it works on Firefox)

I'm really new to SST. 
From a very first look, I wonder if the problem is  caused by the missing `Access-Control-Allow-Private-Network: true` header.

More details https://developer.chrome.com/blog/private-network-access-preflight/

**Comment by jayair** [comment]
Which version of Chrome is this?

**Comment by flea89** [comment]
Crome Version 107.0.5304.110 (Official Build) (x86_64)

**Comment by karan-pathak** [comment]
You can try installing mkcert. It worked for me on chrome.
Find detailed steps to do this under the heading "Safari and Brave" on https://docs.sst.dev/console

**Comment by yasirtrimulabs** [comment]
Same here I am getting CORS errors in edge, chrome, firefox and blocked contect in safari, but I am on Mac with Intel

**Comment by shelbyspeegle** [comment]
this seems like ancient history - M1 user here and works for me out of the box - should we archive?

**Comment by jayair** [comment]
Yup also we have this https://sst.dev/docs/reference/cli#cert
